### PR TITLE
fix: fix bonus damage types

### PR DESCRIPTION
**Pull request by DevChromium**
# Cause
Wynn API changed the field names from `bonus<element>Damage` to `<element>DamageBonus`
Wynn API

# Fix 
Added new strings to match against, also changed the defence bonuses just in case they change them in the future to comply with the naming standard of `<element><type>Bonus`
Changes

### CODE REVIEW

**Review by RuKira — DISMISSED** [review]
@DevScyu This good to me, going through the cause and effect this seems to be correct change of course

**Review by RuKira — COMMENTED** [review]
@DevChromium Am I to assume this is the last of the changes? if so I will approve of this PR

**Comment by DevChromium** [comment]
> @DevChromium Am I to assume this is the last of the changes? if so I will approve of this PR
Like did you find the rest?

Everything changed in this PR should be all fields changed in the WynnAPI.

**Review by RuKira — APPROVED** [review]
With the recent reply, I approve of these name changes, nothing too broken, and seems to still work in local testing.

**Pull request merged**
