### PR TITLE
Ordering of the new stats

### PR DESCRIPTION
**Pull request by magicus**
This is a partial fix for Athena for the new stats (identifications) that was added in 2.0. A handful of them were already added, but one was duplicated, and the other in an inconsistent order (the element ordering did not match the one used everywhere else).

From an interop perspective, this list is the paramount change. The position of stats on this list determines how we encode gear items on the chat, so this must match the corresponding list in Artemis. So what you see here is basically a "backport" of the additions I did in Artemis, where I tried to align the new stats as closely as I could to the method used for the old stats.

However, this is not the full solution of what needs to support these new stats. You need also to add the ingame-lore tag (THE UPPERCASE ONE), and you need to parse the corresponding tag from the Wynncraft API.

### CODE REVIEW

**Comment by magicus** [comment]
Since I think you created a mess of the situation by renaming the tags, I'm not very fond of the idea of fixing this for Athena/Legacy, so I'll leave it up to someone else. But I will help you out by posting a list of the corresponding api tags, in the same order as the Athena tags in this post, so you can compare them side-by-side to figure out the api tags.

If you want, I could also try to extract the display name and ingame-lore tag from Artemis, in the same order, so you can match them as well. Let me know if you want me to attempt that.

**Comment by magicus** [comment]
```
"attackSpeedBonus",
"mainAttackDamageBonusRaw",
"mainAttackDamageBonus",
"mainAttackNeutralDamageBonusRaw",
"mainAttackNeutralDamageBonus",
"mainAttackElementalDamageBonusRaw",
"mainAttackElementalDamageBonus",
"mainAttackEarthDamageBonusRaw",
"mainAttackEarthDamageBonus",
"mainAttackThunderDamageBonusRaw",
"mainAttackThunderDamageBonus",
"mainAttackWaterDamageBonusRaw",
"mainAttackWaterDamageBonus",
"mainAttackFireDamageBonusRaw",
"mainAttackFireDamageBonus",
"mainAttackAirDamageBonusRaw",
"mainAttackAirDamageBonus",
"spellDamageBonusRaw",
"spellDamageBonus",
"spellNeutralDamageBonusRaw",
"spellNeutralDamageBonus",
"spellElementalDamageBonusRaw",
"spellElementalDamageBonus",
"spellEarthDamageBonusRaw",
"spellEarthDamageBonus",
"spellThunderDamageBonusRaw",
"spellThunderDamageBonus",
"spellWaterDamageBonusRaw",
"spellWaterDamageBonus",
"spellFireDamageBonusRaw",
"spellFireDamageBonus",
"spellAirDamageBonusRaw",
"spellAirDamageBonus",
"", // delimiter
"healthBonus",
"healthRegenRaw",
"healthRegen",
"lifeSteal",
"manaRegen",
"manaSteal",
"", // delimiter
"damageBonusRaw",
"damageBonus",
"neutralDamageBonusRaw",
"neutralDamageBonus",
"elementalDamageBonusRaw",
"elementalDamageBonus",
"earthDamageBonusRaw",
"earthDamageBonus",
"thunderDamageBonusRaw",
"thunderDamageBonus",
"waterDamageBonusRaw",
"waterDamageBonus",
"fireDamageBonusRaw",
"fireDamageBonus",
"airDamageBonusRaw",
"airDamageBonus",
"", // delimiter
"bonusEarthDefense",
"bonusThunderDefense",
"bonusWaterDefense",
"bonusFireDefense",
"bonusAirDefense",
"", // delimiter
"exploding",
"poison",
"thorns",
"reflection",
"", // delimiter
"speed",
"sprint",
"sprintRegen",
"jumpHeight",
"", // delimiter
"soulPoints",
"lootBonus",
"lootQuality",
"emeraldStealing",
"xpBonus",
"gatherXpBonus",
"gatherSpeed",
"", // delimiter
"spellCostRaw1",
"spellCostPct1",
"spellCostRaw2",
"spellCostPct2",
"spellCostRaw3",
"spellCostPct3",
"spellCostRaw4",
"spellCostPct4"
```

**Comment by magicus** [comment]
I did not notice that this was never merged. Without this, chat item exchanges between legacy and artemis risks being broken.

**Review by DevChromium — APPROVED** [review]
LGTM

**Review by DevScyu — APPROVED** [review]

**Pull request merged**
